###
### Author: ngoanh2n
### https://circleci.com/docs
###
version: 2.1

executors:
  executor_macos:
    # https://circleci.com/docs/using-macos
    macos:
      xcode: 15.0.0
      resource_class: macos.x86.medium.gen2
    shell: /bin/bash
  executor_linux:
    # https://circleci.com/docs/using-linuxvm
    # https://circleci.com/developer/machine/image/ubuntu-2004
    machine:
      image: ubuntu-2004:current
      resource_class: medium
    shell: /bin/bash
  executor_windows:
    # https://circleci.com/docs/using-windows
    # https://circleci.com/developer/machine/image/windows-server-2022-gui
    machine:
      image: windows-server-2022-gui:current
      resource_class: windows.medium
    shell: bash.exe

commands:
  env_prepare:
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            java --version
            chmod +x gradlew
  test_execute:
    steps:
      - run:
          name: Execute the test
          command: ./gradlew clean test
          when: always

jobs:
  build_and_test:
    parameters:
      os: { type: executor }
    executor: <<parameters.os>>
    steps:
      - env_prepare
      - test_execute

workflows:
  test_execution:
    jobs:
      - build_and_test:
          name: <<matrix.os>>
          filters:
            branches:
              only: master
          matrix:
            parameters:
              os:
                - executor_macos
                - executor_linux
                - executor_windows
