###
### author: Ho Huu Ngoan (ngoanh2n@gmail.com)
###
version: 2.1

executors:
  executor_macos:
    macos:
      xcode: 13.4.1
    shell: /bin/bash
    resource_class: medium
  executor_linux:
    machine:
      image: ubuntu-2004:2022.07.1
    shell: /bin/bash
    resource_class: medium
  executor_windows:
    machine:
      image: windows-server-2022-gui:current
    shell: bash.exe
    resource_class: windows.medium

commands:
  env_prepare:
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            chmod +x gradlew
  test_execute:
    steps:
      - run:
          name: Execute the test
          command: ./gradlew clean test
          when: always

jobs:
  build_and_test:
    parameters:
      os: { type: executor }
    executor: <<parameters.os>>
    steps:
      - env_prepare
      - test_execute

workflows:
  test_execution:
    jobs:
      - build_and_test:
          name: <<matrix.os>>
          filters:
            branches:
              only: master
          matrix:
            parameters:
              os:
                - executor_macos
                - executor_linux
                - executor_windows
