#
# Author: ngoanh2n
#
[versions]
commons           = "1.6.0"
allure-java       = "2.29.0"
aspectj           = "1.9.22.1"
slf4j             = "2.0.16"
junit-jupiter     = "5.10.3"
junit-platform    = "1.10.3"
allure-plugin     = "2.12.0"

[libraries]
commons                 = { group = "com.github.ngoanh2n", name = "commons",                 version.ref = "commons"        }
allure-java-commons     = { group = "io.qameta.allure",    name = "allure-java-commons",     version.ref = "allure-java"    }
allure-junit5           = { group = "io.qameta.allure",    name = "allure-junit5",           version.ref = "allure-java"    }
slf4j-log4j12           = { group = "org.slf4j",           name = "slf4j-log4j12",           version.ref = "slf4j"          }
junit-jupiter-api       = { group = "org.junit.jupiter",   name = "junit-jupiter-api",       version.ref = "junit-jupiter"  }
junit-jupiter-engine    = { group = "org.junit.jupiter",   name = "junit-jupiter-engine",    version.ref = "junit-jupiter"  }
junit-platform-launcher = { group = "org.junit.platform",  name = "junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
allure = { id = "io.qameta.allure", version.ref = "allure-plugin" }
