###
### Author: ngoanh2n
### https://docs.github.com/en/actions
### https://github.com/marketplace?type=actions
###
name: Test
on:
  push:
    branches: [ release ]
  workflow_dispatch:
jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
        jdk: [ 17 ]
    env:
      JUNIT_REPORT_NAME: report_${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - name: Execute the test
        run: ./gradlew clean test
      - name: Summarize JUnit report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: ${{ env.JUNIT_REPORT_NAME }}
          report_paths: build/reports/test/TEST-*.xml
